"""
Invoicing service — GRA e-VAT compliant invoice generation.
Handles: tax computation, QR payload, verification ID, number sequencing.
Heavy assets (PDF, QR images) are generated by Celery workers.
"""

import hashlib
import json
from decimal import ROUND_HALF_UP, Decimal
from uuid import UUID

import structlog
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from apps.api.core.config import get_settings
from apps.api.core.exceptions import LimitExceededError, NotFoundError
from apps.api.modules.business.models import Business
from apps.api.modules.invoicing.models import Invoice, InvoiceItem
from apps.api.modules.sales.models import Sale
from apps.api.workers.dispatch import enqueue_task

logger = structlog.get_logger()
settings = get_settings()

TWO_PLACES = Decimal("0.01")


def _round(v: Decimal) -> Decimal:
    return v.quantize(TWO_PLACES, rounding=ROUND_HALF_UP)


class InvoicingService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    async def generate_from_sale(self, sale_id: UUID, business_id: UUID) -> Invoice:
        """
        Primary entry point called by Celery task after a sale is recorded.
        Builds a fully GRA e-VAT compliant invoice.
        """
        # Load sale with items
        sale_result = await self.db.execute(select(Sale).where(Sale.id == sale_id))
        sale = sale_result.scalar_one_or_none()
        if not sale:
            raise NotFoundError("Sale", str(sale_id))

        business_result = await self.db.execute(select(Business).where(Business.id == business_id))
        business = business_result.scalar_one_or_none()
        if not business:
            raise NotFoundError("Business", str(business_id))

        # Load sale items
        from apps.api.modules.sales.models import Receivable, SaleItem

        items_result = await self.db.execute(select(SaleItem).where(SaleItem.sale_id == sale_id))
        sale_items = list(items_result.scalars().all())
        receivable = await self.db.scalar(select(Receivable).where(Receivable.sale_id == sale_id))

        # Compute GRA tax breakdown. sell_price is tax-INCLUSIVE so we extract
        # the pre-tax base rather than adding tax on top of the sale total.
        from apps.api.modules.tax.rate_config import get_effective_rates

        rates = await get_effective_rates(business_id, self.db)
        total = sale.total  # what the customer actually paid (tax-inclusive)
        combined_rate = rates.vat_rate + rates.nhil_rate + rates.getfund_rate + rates.covid_levy_rate
        subtotal = _round(total / (1 + combined_rate))  # pre-tax base
        vat = _round(subtotal * rates.vat_rate)
        nhil = _round(subtotal * rates.nhil_rate)
        getfund = _round(subtotal * rates.getfund_rate)
        covid = _round(subtotal * rates.covid_levy_rate)

        invoice_number = await self._next_invoice_number(business_id)
        verification_id = self._generate_verification_id(
            business, invoice_number, total, sale.created_at.isoformat()
        )
        qr_payload = self._build_gra_qr_payload(
            business,
            verification_id,
            total,
            vat,
            sale.created_at.isoformat(),
            len(sale_items),
        )
        digital_signature = self._sign_payload(qr_payload)
        from libs.qr_generator.ghqr import generate_ghqr_payload

        ghqr_payload = generate_ghqr_payload(business, total)

        # Determine customer info
        customer_name = None
        customer_phone = None
        if sale.customer_id:
            from apps.api.modules.sales.models import Customer

            cust_result = await self.db.execute(
                select(Customer).where(Customer.id == sale.customer_id)
            )
            cust = cust_result.scalar_one_or_none()
            if cust:
                customer_name = cust.name
                customer_phone = cust.phone

        invoice = Invoice(
            business_id=business_id,
            sale_id=sale_id,
            invoice_number=invoice_number,
            type="receipt" if sale.payment_method != "credit" else "invoice",
            status="paid" if sale.balance_due == 0 else "issued",
            supplier_tin=business.tin,
            supplier_name=business.name,
            supplier_address=business.address,
            customer_name=customer_name,
            customer_phone=customer_phone,
            subtotal=subtotal,
            vat_amount=vat,
            nhil_amount=nhil,
            getfund_amount=getfund,
            covid_levy=covid,
            total=total,
            due_date=receivable.due_date if receivable else None,
            amount_paid=sale.amount_paid,
            balance_due=sale.balance_due,
            qr_payload=qr_payload,
            digital_signature=digital_signature,
            verification_id=verification_id,
            ghqr_payload=ghqr_payload,
        )
        self.db.add(invoice)
        await self.db.flush([invoice])

        # Invoice line items
        for si in sale_items:
            ii = InvoiceItem(
                invoice_id=invoice.id,
                description=si.description,
                qty=si.qty,
                unit_price=si.unit_price,
                line_total=si.line_total,
                vat_rate=rates.vat_rate * 100,
                vat_amount=_round(si.line_total * rates.vat_rate),
            )
            self.db.add(ii)

        await self.db.flush()
        logger.info("invoice.generated", invoice_id=str(invoice.id), invoice_number=invoice_number)

        # Queue asset generation (PDF + QR images) — fire and forget
        try:
            from apps.api.workers.tasks.invoicing_tasks import (
                generate_invoice_assets,
            )

            enqueue_task(generate_invoice_assets, str(invoice.id))
        except Exception as e:
            logger.warning("invoice.asset_task_failed", error=str(e))

        return invoice

    async def _next_invoice_number(self, business_id: UUID) -> str:
        """Sequential invoice number per business: SME-{YYYYMM}-{sequence}"""
        from datetime import datetime, timezone

        now = datetime.now(timezone.utc)
        prefix = f"SME-{now.strftime('%Y%m')}"

        count_result = await self.db.execute(
            select(func.count(Invoice.id)).where(
                Invoice.business_id == business_id,
                Invoice.invoice_number.like(f"{prefix}%"),
            )
        )
        seq = (count_result.scalar() or 0) + 1
        return f"{prefix}-{seq:05d}"

    def _generate_verification_id(
        self,
        business: Business,
        invoice_number: str,
        total: Decimal,
        issued_key: str | None = None,
    ) -> str:
        """Deterministic verification ID for GRA: hash of TIN + invoice number + total."""
        raw = f"{business.tin or 'NOTIN'}:{invoice_number}:{total}:{issued_key or ''}"
        return hashlib.sha256(raw.encode()).hexdigest()[:20].upper()

    def _build_gra_qr_payload(
        self,
        business: Business,
        verification_id: str,
        total: Decimal,
        vat: Decimal,
        issued_at: str | None,
        item_count: int,
    ) -> str:
        """Build GRA e-VAT QR payload (JSON-encoded verification data)."""
        payload = {
            "tin": business.tin or "",
            "vno": verification_id,
            "date": issued_at,
            "total": str(total),
            "vat": str(vat),
            "items": item_count,
        }
        return json.dumps(payload, separators=(",", ":"))

    def _sign_payload(self, payload: str) -> str:
        """HMAC-SHA256 signature for QR payload integrity."""
        import hmac

        sig = hmac.new(
            settings.SECRET_KEY.encode(),
            payload.encode(),
            hashlib.sha256,
        ).hexdigest()
        return sig[:32]

    async def get_invoice(self, business_id: UUID, invoice_id: UUID) -> Invoice:
        result = await self.db.execute(
            select(Invoice)
            .where(Invoice.id == invoice_id, Invoice.business_id == business_id)
            .options(selectinload(Invoice.line_items))
        )
        inv = result.scalar_one_or_none()
        if not inv:
            raise NotFoundError("Invoice", str(invoice_id))
        return inv

    async def get_invoice_by_sale(self, business_id: UUID, sale_id: UUID) -> Invoice:
        result = await self.db.execute(
            select(Invoice)
            .where(Invoice.business_id == business_id, Invoice.sale_id == sale_id)
            .options(selectinload(Invoice.line_items))
            .order_by(Invoice.issued_at.desc())
        )
        inv = result.scalar_one_or_none()
        if not inv:
            raise NotFoundError("Invoice for sale", str(sale_id))
        return inv

    async def list_invoices(
        self,
        business_id: UUID,
        status: str | None = None,
        invoice_type: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[Invoice], int]:
        """Return paginated invoices for a business with optional filters."""
        from datetime import date as date_type

        from sqlalchemy import Date, cast

        q = (
            select(Invoice)
            .where(Invoice.business_id == business_id)
            .options(selectinload(Invoice.line_items))
        )
        count_q = select(func.count(Invoice.id)).where(Invoice.business_id == business_id)

        if status:
            q = q.where(Invoice.status == status)
            count_q = count_q.where(Invoice.status == status)
        if invoice_type:
            q = q.where(Invoice.type == invoice_type)
            count_q = count_q.where(Invoice.type == invoice_type)
        if from_date:
            start = date_type.fromisoformat(from_date)
            q = q.where(cast(Invoice.issued_at, Date) >= start)
            count_q = count_q.where(cast(Invoice.issued_at, Date) >= start)
        if to_date:
            end = date_type.fromisoformat(to_date)
            q = q.where(cast(Invoice.issued_at, Date) <= end)
            count_q = count_q.where(cast(Invoice.issued_at, Date) <= end)

        q = q.order_by(Invoice.issued_at.desc()).limit(limit).offset(offset)

        results = await self.db.execute(q)
        count_result = await self.db.execute(count_q)
        return list(results.scalars().all()), (count_result.scalar() or 0)

    async def generate_standalone(
        self,
        business_id: UUID,
        supplier_name: str,
        supplier_tin: str | None,
        supplier_address: str | None,
        customer_name: str | None,
        customer_tin: str | None,
        customer_phone: str | None,
        customer_address: str | None,
        line_items: list[dict],
        invoice_type: str = "invoice",
        customer_email: str | None = None,
    ) -> Invoice:
        """
        Create an invoice not linked to any sale — for B2B, proforma, or manual billing.
        line_items: [{"description": str, "qty": Decimal, "unit_price": Decimal, "unit": str|None}]

        NOTE: unlike generate_from_sale (which treats Item.sell_price as tax-
        INCLUSIVE and extracts tax from the total), unit_price here is tax-
        EXCLUSIVE — a pre-tax base entered manually on the invoice form — and tax
        is added on top. This matches the mobile new-invoice.tsx form, which
        labels the computed total "Subtotal" and notes VAT/NHIL/GETFund are
        "calculated automatically". This is an intentional, separate pricing
        convention for manual invoices, not a bug — see Item.sell_price docstring.
        """
        await self._check_invoice_limit(business_id)
        business_result = await self.db.execute(select(Business).where(Business.id == business_id))
        business = business_result.scalar_one_or_none()
        if not business:
            raise NotFoundError("Business", str(business_id))

        from apps.api.modules.tax.rate_config import get_effective_rates

        rates = await get_effective_rates(business_id, self.db)
        subtotal = sum((item["qty"] * item["unit_price"]) for item in line_items)
        subtotal = _round(Decimal(str(subtotal)))
        vat = _round(subtotal * rates.vat_rate)
        nhil = _round(subtotal * rates.nhil_rate)
        getfund = _round(subtotal * rates.getfund_rate)
        covid = _round(subtotal * rates.covid_levy_rate)
        total = subtotal + vat + nhil + getfund + covid

        invoice_number = await self._next_invoice_number(business_id)
        verification_id = self._generate_verification_id(business, invoice_number, total)
        qr_payload = self._build_gra_qr_payload(
            business, verification_id, total, vat, None, len(line_items)
        )
        digital_signature = self._sign_payload(qr_payload)
        from libs.qr_generator.ghqr import generate_ghqr_payload

        ghqr_payload = generate_ghqr_payload(business, total)

        invoice = Invoice(
            business_id=business_id,
            sale_id=None,
            invoice_number=invoice_number,
            type=invoice_type,
            status="issued",
            supplier_tin=supplier_tin or business.tin,
            supplier_name=supplier_name or business.name,
            supplier_address=supplier_address or business.address,
            customer_name=customer_name,
            customer_tin=customer_tin,
            customer_phone=customer_phone,
            customer_email=customer_email,
            customer_address=customer_address,
            subtotal=subtotal,
            vat_amount=vat,
            nhil_amount=nhil,
            getfund_amount=getfund,
            covid_levy=covid,
            total=total,
            qr_payload=qr_payload,
            digital_signature=digital_signature,
            verification_id=verification_id,
            ghqr_payload=ghqr_payload,
        )
        self.db.add(invoice)
        await self.db.flush([invoice])

        for item in line_items:
            qty = Decimal(str(item["qty"]))
            unit_price = Decimal(str(item["unit_price"]))
            line_total = _round(qty * unit_price)
            ii = InvoiceItem(
                invoice_id=invoice.id,
                description=item["description"],
                qty=qty,
                unit=item.get("unit"),
                unit_price=unit_price,
                line_total=line_total,
                vat_rate=rates.vat_rate * 100,
                vat_amount=_round(line_total * rates.vat_rate),
            )
            self.db.add(ii)

        await self.db.flush()
        logger.info(
            "invoice.standalone_generated", invoice_id=str(invoice.id), number=invoice_number
        )

        try:
            from apps.api.workers.tasks.invoicing_tasks import generate_invoice_assets

            enqueue_task(generate_invoice_assets, str(invoice.id))
        except Exception as e:
            logger.warning("invoice.asset_task_failed", error=str(e))

        await self._attach_paystack_payment_page(invoice)
        return invoice

    async def create_debit_note(
        self,
        business_id: UUID,
        invoice_id: UUID,
        line_items: list[dict],
    ) -> Invoice:
        """
        Issue a linked debit note that increases the amount due on an immutable invoice.

        Uses the same tax-EXCLUSIVE unit_price convention as generate_standalone
        (tax added on top of the entered price), not the tax-inclusive model used
        by generate_from_sale — see the note there and Item.sell_price's docstring.
        """
        await self._check_invoice_limit(business_id)
        original = await self.get_invoice(business_id, invoice_id)
        if original.status in ("cancelled", "voided"):
            from apps.api.core.exceptions import ConflictError

            raise ConflictError("Cannot issue a debit note for a cancelled invoice")

        business_result = await self.db.execute(select(Business).where(Business.id == business_id))
        business = business_result.scalar_one_or_none()
        if not business:
            raise NotFoundError("Business", str(business_id))

        from apps.api.modules.tax.rate_config import get_effective_rates
        from libs.qr_generator.ghqr import generate_ghqr_payload

        rates = await get_effective_rates(business_id, self.db)
        subtotal = _round(sum((item["qty"] * item["unit_price"]) for item in line_items))
        vat = _round(subtotal * rates.vat_rate)
        nhil = _round(subtotal * rates.nhil_rate)
        getfund = _round(subtotal * rates.getfund_rate)
        covid = _round(subtotal * rates.covid_levy_rate)
        total = subtotal + vat + nhil + getfund + covid
        invoice_number = await self._next_invoice_number(business_id)
        verification_id = self._generate_verification_id(business, invoice_number, total)
        qr_payload = self._build_gra_qr_payload(
            business, verification_id, total, vat, None, len(line_items)
        )

        note = Invoice(
            business_id=business_id,
            sale_id=original.sale_id,
            original_invoice_id=original.id,
            invoice_number=invoice_number,
            type="debit_note",
            status="issued",
            supplier_tin=original.supplier_tin,
            supplier_name=original.supplier_name,
            supplier_address=original.supplier_address,
            customer_name=original.customer_name,
            customer_tin=original.customer_tin,
            customer_phone=original.customer_phone,
            customer_address=original.customer_address,
            subtotal=subtotal,
            vat_amount=vat,
            nhil_amount=nhil,
            getfund_amount=getfund,
            covid_levy=covid,
            total=total,
            qr_payload=qr_payload,
            digital_signature=self._sign_payload(qr_payload),
            verification_id=verification_id,
            ghqr_payload=generate_ghqr_payload(business, total),
        )
        self.db.add(note)
        await self.db.flush([note])

        for item in line_items:
            qty = Decimal(str(item["qty"]))
            unit_price = Decimal(str(item["unit_price"]))
            line_total = _round(qty * unit_price)
            self.db.add(
                InvoiceItem(
                    invoice_id=note.id,
                    description=item["description"],
                    qty=qty,
                    unit=item.get("unit"),
                    unit_price=unit_price,
                    line_total=line_total,
                    vat_rate=rates.vat_rate * 100,
                    vat_amount=_round(line_total * rates.vat_rate),
                )
            )

        await self.db.flush()
        logger.info("invoice.debit_note_issued", original=str(invoice_id), debit=str(note.id))
        return note

    async def _check_invoice_limit(self, business_id: UUID) -> None:
        """Enforce the plan's monthly standalone invoice cap."""
        from datetime import datetime, timezone

        from apps.api.modules.billing.models import PLANS
        from apps.api.modules.billing.service import BillingService

        billing = BillingService(self.db)
        month_start = datetime.now(timezone.utc).replace(
            day=1, hour=0, minute=0, second=0, microsecond=0
        )
        month_count = (
            await self.db.execute(
                select(func.count(Invoice.id)).where(
                    Invoice.business_id == business_id,
                    Invoice.type != "receipt",
                    Invoice.issued_at >= month_start,
                )
            )
        ).scalar_one()
        if not await billing.check_limit(business_id, "monthly_invoices", month_count or 0):
            sub = await billing.get_subscription(business_id)
            limit = PLANS.get(sub.plan, PLANS["free"]).get("monthly_invoices", 0)
            raise LimitExceededError("monthly invoices", limit)

    async def void_invoice(self, business_id: UUID, invoice_id: UUID, user_id: UUID) -> Invoice:
        """
        Void an issued invoice and automatically issue a matching credit note.
        Voiding a paid invoice returns it to 'cancelled'; linked sale is NOT auto-voided.
        """
        from apps.api.core.audit import audit

        invoice = await self.get_invoice(business_id, invoice_id)
        if invoice.status in ("cancelled", "voided"):
            from apps.api.core.exceptions import ConflictError

            raise ConflictError(f"Invoice {invoice.invoice_number} is already {invoice.status}")

        invoice.status = "cancelled"
        await self.db.flush([invoice])
        await audit(
            self.db,
            "invoice.voided",
            "Invoice",
            invoice.id,
            user_id,
            business_id,
            after={"status": "cancelled"},
        )

        # Issue a balancing credit note
        credit_number = await self._next_invoice_number(business_id)
        credit_note = Invoice(
            business_id=business_id,
            sale_id=invoice.sale_id,
            original_invoice_id=invoice.id,
            invoice_number=credit_number,
            type="credit_note",
            status="issued",
            supplier_tin=invoice.supplier_tin,
            supplier_name=invoice.supplier_name,
            supplier_address=invoice.supplier_address,
            customer_name=invoice.customer_name,
            customer_tin=invoice.customer_tin,
            customer_phone=invoice.customer_phone,
            customer_address=invoice.customer_address,
            subtotal=-invoice.subtotal,
            vat_amount=-invoice.vat_amount,
            nhil_amount=-invoice.nhil_amount,
            getfund_amount=-invoice.getfund_amount,
            covid_levy=-invoice.covid_levy,
            total=-invoice.total,
            verification_id=None,
        )
        business_result = await self.db.execute(select(Business).where(Business.id == business_id))
        business = business_result.scalar_one_or_none()
        if not business:
            raise NotFoundError("Business", str(business_id))
        credit_note.verification_id = self._generate_verification_id(
            business, credit_number, -invoice.total
        )
        credit_note.qr_payload = self._build_gra_qr_payload(
            business,
            credit_note.verification_id,
            -invoice.total,
            -invoice.vat_amount,
            None,
            len(invoice.line_items),
        )
        credit_note.digital_signature = self._sign_payload(credit_note.qr_payload)
        from libs.qr_generator.ghqr import generate_ghqr_payload

        credit_note.ghqr_payload = generate_ghqr_payload(business, -invoice.total)
        self.db.add(credit_note)
        await self.db.flush([credit_note])
        for original_item in invoice.line_items:
            self.db.add(
                InvoiceItem(
                    invoice_id=credit_note.id,
                    description=original_item.description,
                    qty=-original_item.qty,
                    unit=original_item.unit,
                    unit_price=original_item.unit_price,
                    line_total=-original_item.line_total,
                    vat_rate=original_item.vat_rate,
                    vat_amount=-original_item.vat_amount,
                )
            )
        await self.db.flush()
        logger.info(
            "invoice.credit_note_issued", original=str(invoice_id), credit=str(credit_note.id)
        )
        return invoice

    # ── Paystack payment page ─────────────────────────────────────────────────

    async def _attach_paystack_payment_page(self, invoice: Invoice) -> None:
        """
        Generate a Paystack hosted payment page for the invoice and store its URL.

        Fail-open: if Paystack is not configured or the API call fails, the
        invoice is returned without a payment URL (does not break invoice creation).
        """
        if not settings.PAYSTACK_SECRET_KEY:
            return
        try:
            from libs.payment_clients.paystack import PaystackClient

            client = PaystackClient()
            ref = str(invoice.id)
            page = await client.create_payment_page(
                name=f"Invoice {invoice.invoice_number}",
                reference=ref,
                description=f"Payment for invoice {invoice.invoice_number} from {invoice.supplier_name}",
                amount_ghs=invoice.total,
            )
            invoice.paystack_payment_url = page.get("url")
            await self.db.flush([invoice])
            logger.info(
                "invoice.payment_page_created",
                invoice_id=str(invoice.id),
                url=invoice.paystack_payment_url,
            )
        except Exception as exc:
            logger.warning(
                "invoice.payment_page_failed",
                invoice_id=str(invoice.id),
                error=str(exc),
            )
