apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: smeflow-aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: af-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: smeflow-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smeflow-secrets
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: smeflow-aws-secrets
    kind: SecretStore
  target:
    name: smeflow-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: smeflow/production/api
