"""initial_schema

Revision ID: 564878921738
Revises: 
Create Date: 2026-06-06 14:59:22.349770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '564878921738'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('commission_rate_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type')
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_device_tokens_token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('lender_partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lender_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('portal_email', sa.String(length=255), nullable=True),
    sa.Column('portal_password_hash', sa.String(length=255), nullable=True),
    sa.Column('must_reset_password', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key_hint', sa.String(length=10), nullable=True),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('paystack_subaccount_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_split_code', sa.String(length=100), nullable=True),
    sa.Column('settlement_bank_code', sa.String(length=20), nullable=True),
    sa.Column('settlement_account_number', sa.String(length=20), nullable=True),
    sa.Column('platform_fee_percent', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lender_partners_lender_id'), 'lender_partners', ['lender_id'], unique=True)
    op.create_index(op.f('ix_lender_partners_portal_email'), 'lender_partners', ['portal_email'], unique=True)
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.create_table('suspension_appeals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspension_appeals_business_id'), 'suspension_appeals', ['business_id'], unique=False)
    op.create_index(op.f('ix_suspension_appeals_status'), 'suspension_appeals', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ghana_card_id', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=12), nullable=True),
    sa.Column('language_pref', sa.String(length=5), server_default='en', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ghana_card_id'),
    sa.UniqueConstraint('tin')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('agent_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('momo_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_applications_status'), 'agent_applications', ['status'], unique=False)
    op.create_index(op.f('ix_agent_applications_user_id'), 'agent_applications', ['user_id'], unique=False)
    op.create_table('agent_payout_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=False),
    sa.Column('transfer_count', sa.Integer(), nullable=False),
    sa.Column('paystack_batch_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('momo_phone', sa.String(length=20), nullable=True),
    sa.Column('momo_provider', sa.String(length=20), nullable=True),
    sa.Column('paystack_recipient_code', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarded_count', sa.Integer(), nullable=False),
    sa.Column('total_commission_earned', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pending_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_paid_out', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('last_payout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('ghana_card_ref', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=150), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('momo_provider', sa.String(length=20), nullable=True),
    sa.Column('tax_vat_status', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('template_slug', sa.String(length=80), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('subscription', sa.String(length=20), nullable=False),
    sa.Column('sub_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ghqr_merchant_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('paystack_customer_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_customer_id', sa.Integer(), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True),
    sa.Column('dva_id', sa.String(length=100), nullable=True),
    sa.Column('dva_account_number', sa.String(length=20), nullable=True),
    sa.Column('dva_account_name', sa.String(length=255), nullable=True),
    sa.Column('dva_bank_name', sa.String(length=100), nullable=True),
    sa.Column('unsettled_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_settled', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settlement_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('settlement_enabled', sa.Boolean(), nullable=False),
    sa.Column('paystack_recipient_code', sa.String(length=100), nullable=True),
    sa.Column('last_settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_business_owner_name')
    )
    op.create_index('uq_business_tin', 'businesses', ['tin'], unique=True, postgresql_where='tin IS NOT NULL')
    op.create_table('loan_products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lender_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('min_amount_ghs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount_ghs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate_annual', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_term_days', sa.Integer(), nullable=False),
    sa.Column('max_term_days', sa.Integer(), nullable=False),
    sa.Column('min_credit_band', sa.String(length=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lender_partners.lender_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_products_lender_id'), 'loan_products', ['lender_id'], unique=False)
    op.create_table('pending_admin_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['platform_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_admin_actions_action_type'), 'pending_admin_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_pending_admin_actions_status'), 'pending_admin_actions', ['status'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referee_phone', sa.String(length=15), nullable=False),
    sa.Column('referee_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reward_granted', sa.Boolean(), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referrer_id', 'referee_phone', name='uq_referral_pair')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('agent_commissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by', sa.UUID(), nullable=True),
    sa.Column('paid_via', sa.String(length=20), nullable=True),
    sa.Column('payout_batch_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['payout_batch_id'], ['agent_payout_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'business_id', 'trigger', name='uq_agent_commission_trigger')
    )
    op.create_index(op.f('ix_agent_commissions_agent_id'), 'agent_commissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_commissions_business_id'), 'agent_commissions', ['business_id'], unique=False)
    op.create_index(op.f('ix_agent_commissions_status'), 'agent_commissions', ['status'], unique=False)
    op.create_table('agent_payout_allocations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('amount_ghs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transfer_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payout_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['agent_payout_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'agent_id', name='uq_allocation_batch_agent')
    )
    op.create_index(op.f('ix_agent_payout_allocations_agent_id'), 'agent_payout_allocations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_payout_allocations_batch_id'), 'agent_payout_allocations', ['batch_id'], unique=False)
    op.create_table('agent_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'year', 'month', name='uq_agent_target_month')
    )
    op.create_index(op.f('ix_agent_targets_agent_id'), 'agent_targets', ['agent_id'], unique=False)
    op.create_table('business_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'manager', 'staff')", name='ck_business_member_role'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_business_member')
    )
    op.create_table('credit_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.String(length=5), nullable=False),
    sa.Column('max_loan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_scores_business_id'), 'credit_scores', ['business_id'], unique=False)
    op.create_index(op.f('ix_credit_scores_computed_at'), 'credit_scores', ['computed_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('reminder_consent', sa.Boolean(), nullable=False),
    sa.Column('reminder_channel', sa.String(length=20), nullable=True),
    sa.Column('reminder_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_consent_source', sa.String(length=80), nullable=True),
    sa.Column('reminder_opt_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index('uq_customer_phone', 'customers', ['business_id', 'phone'], unique=True, postgresql_where='phone IS NOT NULL')
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('pay_type', sa.String(length=20), nullable=False),
    sa.Column('base_pay', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('momo_phone', sa.String(length=15), nullable=True),
    sa.Column('momo_provider', sa.String(length=20), nullable=True),
    sa.Column('paystack_recipient_code', sa.String(length=100), nullable=True),
    sa.Column('tier2_enrolled', sa.Boolean(), nullable=False),
    sa.Column('tier2_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tier2_provider', sa.String(length=100), nullable=True),
    sa.Column('ssnit_number', sa.String(length=20), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_business_id'), 'employees', ['business_id'], unique=False)
    op.create_table('item_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_category_name')
    )
    op.create_index(op.f('ix_item_categories_business_id'), 'item_categories', ['business_id'], unique=False)
    op.create_table('kyc_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ghana_card_id', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('business_registration_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_kyc_business')
    )
    op.create_index(op.f('ix_kyc_verifications_business_id'), 'kyc_verifications', ['business_id'], unique=False)
    op.create_index(op.f('ix_kyc_verifications_user_id'), 'kyc_verifications', ['user_id'], unique=False)
    op.create_table('lender_consents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'lender_id', name='uq_lender_consent')
    )
    op.create_index(op.f('ix_lender_consents_business_id'), 'lender_consents', ['business_id'], unique=False)
    op.create_table('merchant_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_role', sa.String(length=20), nullable=True),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('action_path', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissal_reason', sa.String(length=500), nullable=True),
    sa.Column('latest_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'dedupe_key', name='uq_merchant_alert_dedupe')
    )
    op.create_index(op.f('ix_merchant_alerts_alert_type'), 'merchant_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_merchant_alerts_business_id'), 'merchant_alerts', ['business_id'], unique=False)
    op.create_index(op.f('ix_merchant_alerts_recipient_user_id'), 'merchant_alerts', ['recipient_user_id'], unique=False)
    op.create_table('merchant_settlements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('destination_phone', sa.String(length=20), nullable=True),
    sa.Column('destination_provider', sa.String(length=20), nullable=True),
    sa.Column('paystack_transfer_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_reference')
    )
    op.create_index(op.f('ix_merchant_settlements_business_id'), 'merchant_settlements', ['business_id'], unique=False)
    op.create_index(op.f('ix_merchant_settlements_paystack_transfer_code'), 'merchant_settlements', ['paystack_transfer_code'], unique=False)
    op.create_index(op.f('ix_merchant_settlements_status'), 'merchant_settlements', ['status'], unique=False)
    op.create_table('momo_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_ref', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider', 'phone', name='uq_momo_account')
    )
    op.create_table('notification_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_business_id'), 'notification_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('event_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_notification_pref_business')
    )
    op.create_index(op.f('ix_notification_preferences_business_id'), 'notification_preferences', ['business_id'], unique=False)
    op.create_table('onboarding_referrals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('business_id', name='uq_referral_business')
    )
    op.create_index(op.f('ix_onboarding_referrals_agent_id'), 'onboarding_referrals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_onboarding_referrals_referral_code'), 'onboarding_referrals', ['referral_code'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_ssnit_employee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_ssnit_employer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_income_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('run_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period_start', 'period_end', name='uq_payroll_run_period')
    )
    op.create_index(op.f('ix_payroll_runs_business_id'), 'payroll_runs', ['business_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('billing_retry_count', sa.Integer(), nullable=False),
    sa.Column('next_billing_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('momo_phone', sa.String(length=15), nullable=True),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_plan_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_email_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_business_id'), 'subscriptions', ['business_id'], unique=True)
    op.create_table('tax_returns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('vat_output', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_input', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_payable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('nhil_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('getfund_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('covid_levy', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gra_ref', sa.String(length=100), nullable=True),
    sa.Column('export_url', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_returns_business_id'), 'tax_returns', ['business_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('daily_rate_override', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_business_id'), 'attendance_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('billing_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_transactions_business_id'), 'billing_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_billing_transactions_subscription_id'), 'billing_transactions', ['subscription_id'], unique=False)
    op.create_table('customer_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(length=80), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('preferred_channel', sa.String(length=20), nullable=False),
    sa.Column('consent_status', sa.String(length=20), nullable=False),
    sa.Column('consent_source', sa.String(length=80), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('related_resource_type', sa.String(length=40), nullable=True),
    sa.Column('related_resource_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_customer_message_idempotency')
    )
    op.create_index(op.f('ix_customer_messages_business_id'), 'customer_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_messages_message_type'), 'customer_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_customer_messages_status'), 'customer_messages', ['status'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_item_sku')
    )
    op.create_index('ix_items_business_active', 'items', ['business_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_items_business_id'), 'items', ['business_id'], unique=False)
    op.create_table('loan_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('credit_score_id', sa.UUID(), nullable=True),
    sa.Column('amount_requested', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_approved', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('term_days', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lender_id', sa.String(length=100), nullable=True),
    sa.Column('partner_ref', sa.String(length=100), nullable=True),
    sa.Column('lender_webhook_url', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('disbursement_phone', sa.String(length=20), nullable=True),
    sa.Column('disbursement_payment_ref', sa.String(length=100), nullable=True),
    sa.Column('disbursement_transfer_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repaid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defaulted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['credit_score_id'], ['credit_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_requests_business_id'), 'loan_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_loan_requests_disbursement_transfer_code'), 'loan_requests', ['disbursement_transfer_code'], unique=False)
    op.create_index(op.f('ix_loan_requests_lender_id'), 'loan_requests', ['lender_id'], unique=False)
    op.create_index(op.f('ix_loan_requests_status'), 'loan_requests', ['status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_business_created', 'sales', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_sale_business_payment_method', 'sales', ['business_id', 'payment_method'], unique=False)
    op.create_index('idx_sale_business_status_created', 'sales', ['business_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_sale_customer_created', 'sales', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_idempotency_key'), 'sales', ['idempotency_key'], unique=True)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_message_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=180), nullable=True),
    sa.Column('failure_category', sa.String(length=60), nullable=True),
    sa.Column('failure_detail', sa.String(length=255), nullable=True),
    sa.Column('fallback_from', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_message_id'], ['customer_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_message_id', 'attempt_number', name='uq_delivery_attempt_number')
    )
    op.create_index(op.f('ix_delivery_attempts_provider_reference'), 'delivery_attempts', ['provider_reference'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('original_invoice_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supplier_tin', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_address', sa.Text(), nullable=True),
    sa.Column('customer_tin', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('nhil_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('getfund_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('covid_levy', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('qr_image_url', sa.Text(), nullable=True),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('verification_id', sa.String(length=100), nullable=True),
    sa.Column('gra_submission_id', sa.String(length=100), nullable=True),
    sa.Column('gra_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ghqr_payload', sa.Text(), nullable=True),
    sa.Column('ghqr_image_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('paystack_payment_url', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'invoice_number', name='uq_invoice_number'),
    sa.UniqueConstraint('verification_id')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_table('lender_loan_revenues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.String(length=100), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_request_id', name='uq_lender_loan_revenue_loan_request')
    )
    op.create_index(op.f('ix_lender_loan_revenues_business_id'), 'lender_loan_revenues', ['business_id'], unique=False)
    op.create_index(op.f('ix_lender_loan_revenues_lender_id'), 'lender_loan_revenues', ['lender_id'], unique=False)
    op.create_index(op.f('ix_lender_loan_revenues_loan_request_id'), 'lender_loan_revenues', ['loan_request_id'], unique=False)
    op.create_index(op.f('ix_lender_loan_revenues_status'), 'lender_loan_revenues', ['status'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminder_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivables_business_id'), 'receivables', ['business_id'], unique=False)
    op.create_table('repayment_instalments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('instalment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('paystack_ref', sa.String(length=255), nullable=True),
    sa.Column('split_code_used', sa.String(length=100), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('collection_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayment_instalments_due_date'), 'repayment_instalments', ['due_date'], unique=False)
    op.create_index(op.f('ix_repayment_instalments_loan_request_id'), 'repayment_instalments', ['loan_request_id'], unique=False)
    op.create_index(op.f('ix_repayment_instalments_paystack_ref'), 'repayment_instalments', ['paystack_ref'], unique=True)
    op.create_index(op.f('ix_repayment_instalments_status'), 'repayment_instalments', ['status'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_item_item_id', 'sale_items', ['item_id'], unique=False)
    op.create_index('idx_sale_item_sale_id', 'sale_items', ['sale_id'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('qty_change', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transactions_business_id'), 'stock_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_created_at'), 'stock_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_transactions_item_id'), 'stock_transactions', ['item_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('processor', sa.String(length=30), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('provider_detail', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('internal_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('provider_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_business_id'), 'payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_external_ref'), 'payments', ['external_ref'], unique=True)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_table('merchant_ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('settlement_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['merchant_settlements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_ledger_entries_business_id'), 'merchant_ledger_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_merchant_ledger_entries_created_at'), 'merchant_ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_merchant_ledger_entries_payment_id'), 'merchant_ledger_entries', ['payment_id'], unique=False)
    op.create_index(op.f('ix_merchant_ledger_entries_settlement_id'), 'merchant_ledger_entries', ['settlement_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ssnit_employee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ssnit_employer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tier2_employee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_business_id'), 'payslips', ['business_id'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_reservation_item_status', 'stock_reservations', ['item_id', 'status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_stock_reservations_business_id'), 'stock_reservations', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_created_at'), 'stock_reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_reservations_item_id'), 'stock_reservations', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_payment_id'), 'stock_reservations', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reservations_payment_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_item_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_created_at'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_business_id'), table_name='stock_reservations')
    op.drop_index('idx_stock_reservation_item_status', table_name='stock_reservations')
    op.drop_table('stock_reservations')
    op.drop_index(op.f('ix_payslips_business_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_merchant_ledger_entries_settlement_id'), table_name='merchant_ledger_entries')
    op.drop_index(op.f('ix_merchant_ledger_entries_payment_id'), table_name='merchant_ledger_entries')
    op.drop_index(op.f('ix_merchant_ledger_entries_created_at'), table_name='merchant_ledger_entries')
    op.drop_index(op.f('ix_merchant_ledger_entries_business_id'), table_name='merchant_ledger_entries')
    op.drop_table('merchant_ledger_entries')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_business_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_stock_transactions_item_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_created_at'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_business_id'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index('idx_sale_item_sale_id', table_name='sale_items')
    op.drop_index('idx_sale_item_item_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_repayment_instalments_status'), table_name='repayment_instalments')
    op.drop_index(op.f('ix_repayment_instalments_paystack_ref'), table_name='repayment_instalments')
    op.drop_index(op.f('ix_repayment_instalments_loan_request_id'), table_name='repayment_instalments')
    op.drop_index(op.f('ix_repayment_instalments_due_date'), table_name='repayment_instalments')
    op.drop_table('repayment_instalments')
    op.drop_index(op.f('ix_receivables_business_id'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_lender_loan_revenues_status'), table_name='lender_loan_revenues')
    op.drop_index(op.f('ix_lender_loan_revenues_loan_request_id'), table_name='lender_loan_revenues')
    op.drop_index(op.f('ix_lender_loan_revenues_lender_id'), table_name='lender_loan_revenues')
    op.drop_index(op.f('ix_lender_loan_revenues_business_id'), table_name='lender_loan_revenues')
    op.drop_table('lender_loan_revenues')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_delivery_attempts_provider_reference'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_sales_idempotency_key'), table_name='sales')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.drop_index('idx_sale_customer_created', table_name='sales')
    op.drop_index('idx_sale_business_status_created', table_name='sales')
    op.drop_index('idx_sale_business_payment_method', table_name='sales')
    op.drop_index('idx_sale_business_created', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_loan_requests_status'), table_name='loan_requests')
    op.drop_index(op.f('ix_loan_requests_lender_id'), table_name='loan_requests')
    op.drop_index(op.f('ix_loan_requests_disbursement_transfer_code'), table_name='loan_requests')
    op.drop_index(op.f('ix_loan_requests_business_id'), table_name='loan_requests')
    op.drop_table('loan_requests')
    op.drop_index(op.f('ix_items_business_id'), table_name='items')
    op.drop_index('ix_items_business_active', table_name='items', postgresql_where='deleted_at IS NULL')
    op.drop_table('items')
    op.drop_index(op.f('ix_customer_messages_status'), table_name='customer_messages')
    op.drop_index(op.f('ix_customer_messages_message_type'), table_name='customer_messages')
    op.drop_index(op.f('ix_customer_messages_business_id'), table_name='customer_messages')
    op.drop_table('customer_messages')
    op.drop_index(op.f('ix_billing_transactions_subscription_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_business_id'), table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_business_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_tax_returns_business_id'), table_name='tax_returns')
    op.drop_table('tax_returns')
    op.drop_index(op.f('ix_subscriptions_business_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payroll_runs_business_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_onboarding_referrals_referral_code'), table_name='onboarding_referrals')
    op.drop_index(op.f('ix_onboarding_referrals_agent_id'), table_name='onboarding_referrals')
    op.drop_table('onboarding_referrals')
    op.drop_index(op.f('ix_notification_preferences_business_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_events_event_type'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_business_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_table('momo_accounts')
    op.drop_index(op.f('ix_merchant_settlements_status'), table_name='merchant_settlements')
    op.drop_index(op.f('ix_merchant_settlements_paystack_transfer_code'), table_name='merchant_settlements')
    op.drop_index(op.f('ix_merchant_settlements_business_id'), table_name='merchant_settlements')
    op.drop_table('merchant_settlements')
    op.drop_index(op.f('ix_merchant_alerts_recipient_user_id'), table_name='merchant_alerts')
    op.drop_index(op.f('ix_merchant_alerts_business_id'), table_name='merchant_alerts')
    op.drop_index(op.f('ix_merchant_alerts_alert_type'), table_name='merchant_alerts')
    op.drop_table('merchant_alerts')
    op.drop_index(op.f('ix_lender_consents_business_id'), table_name='lender_consents')
    op.drop_table('lender_consents')
    op.drop_index(op.f('ix_kyc_verifications_user_id'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_business_id'), table_name='kyc_verifications')
    op.drop_table('kyc_verifications')
    op.drop_index(op.f('ix_item_categories_business_id'), table_name='item_categories')
    op.drop_table('item_categories')
    op.drop_index(op.f('ix_employees_business_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('uq_customer_phone', table_name='customers', postgresql_where='phone IS NOT NULL')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_credit_scores_computed_at'), table_name='credit_scores')
    op.drop_index(op.f('ix_credit_scores_business_id'), table_name='credit_scores')
    op.drop_table('credit_scores')
    op.drop_table('business_members')
    op.drop_index(op.f('ix_agent_targets_agent_id'), table_name='agent_targets')
    op.drop_table('agent_targets')
    op.drop_index(op.f('ix_agent_payout_allocations_batch_id'), table_name='agent_payout_allocations')
    op.drop_index(op.f('ix_agent_payout_allocations_agent_id'), table_name='agent_payout_allocations')
    op.drop_table('agent_payout_allocations')
    op.drop_index(op.f('ix_agent_commissions_status'), table_name='agent_commissions')
    op.drop_index(op.f('ix_agent_commissions_business_id'), table_name='agent_commissions')
    op.drop_index(op.f('ix_agent_commissions_agent_id'), table_name='agent_commissions')
    op.drop_table('agent_commissions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_pending_admin_actions_status'), table_name='pending_admin_actions')
    op.drop_index(op.f('ix_pending_admin_actions_action_type'), table_name='pending_admin_actions')
    op.drop_table('pending_admin_actions')
    op.drop_index(op.f('ix_loan_products_lender_id'), table_name='loan_products')
    op.drop_table('loan_products')
    op.drop_index('uq_business_tin', table_name='businesses', postgresql_where='tin IS NOT NULL')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('agent_payout_batches')
    op.drop_index(op.f('ix_agent_applications_user_id'), table_name='agent_applications')
    op.drop_index(op.f('ix_agent_applications_status'), table_name='agent_applications')
    op.drop_table('agent_applications')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suspension_appeals_status'), table_name='suspension_appeals')
    op.drop_index(op.f('ix_suspension_appeals_business_id'), table_name='suspension_appeals')
    op.drop_table('suspension_appeals')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    op.drop_index(op.f('ix_lender_partners_portal_email'), table_name='lender_partners')
    op.drop_index(op.f('ix_lender_partners_lender_id'), table_name='lender_partners')
    op.drop_table('lender_partners')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_table('commission_rate_configs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
