"""add customer email fields to invoices and customer_messages

Revision ID: d0326036c412
Revises: c7a1f2b9d3e4
Create Date: 2026-08-11 16:21:26.642867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0326036c412'
down_revision: Union[str, None] = 'c7a1f2b9d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_messages', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('customer_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'customer_email')
    op.drop_column('customer_messages', 'recipient_email')
    # ### end Alembic commands ###
